name: Maven CI/CD Project-simple

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Clean Target Directory
      run: rm -rf /home/runner/work/Telus-project/Telus-project/webapp/target/*

    - name: Build project with Maven
      run: mvn clean install --file pom.xml

    - name: Create Directory if Not Exists
      run: |
        if [ ! -d /home/runner/work/Telus-project/Telus-project/webapp/target/webapp.war ]; then
          mkdir -p /home/runner/work/Telus-project/Telus-project/webapp/target/webapp.war
        fi

    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: storage


      
      
    # - name: List generated WAR files
    #   run: ls -l server/src/.m2

    # - name: Deploy to Artifactory
    #   uses: jfrog/setup-jfrog-cli@v3

    # - name: jfrog-version
    #   run: jf --version

    # - name: j-frog-integration
    #   uses: jfrog/setup-jfrog-cli@v3
    #   with:
    #     jfrog_url: ${{ secrets.JF_URL }}
    #        # JFrog Platform access token
    #     JF_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
    #     JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}  
    #     JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

    
