name: Maven CI/CD Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build project with Maven
      run: mvn clean package --file pom.xml

    - name: Publish Artifact to Nexus Artifactory
      run: |
        curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD --request POST \
          --url "http://3.85.171.142:8081/java-project-artifact/http:/3.85.171.142:8081/repository/java-project-artifact/com.example.maven-project/maven-project/1.0-SNAPSHOT/maven-project-1.0-SNAPSHOT.war" \
          --data-binary "@target/maven-project-1.0-SNAPSHOT.war"
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}



      

    
