name: Maven CI/CD Project-simple

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build project with Maven
      run: mvn clean install --file pom.xml

    - name: List generated WAR files
      run: ls -l server/src/.m2

    - name: Deploy to Artifactory
      uses: jfrog/setup-jfrog-cli@v3

    - name: jfrog-version
      run: jf --version

    - name: j-frog-integration
      uses: jfrog/setup-jfrog-cli@v3
      with:
        jfrog_url: ${{ secrets.JF_URL }}
           # JFrog Platform access token
        JF_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
        JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}  
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

    - name: Publish to Artifactory
      run: |
        jf rt u "server/src/.m2/app.war" "example-repo-local/" --build-name="my-build" --build-number=1 --url=http://18.204.209.62:8081/
